packages:
  - apps/*
  - packages/*
  - tools/*
allowBuilds:
  bun: true
  msgpackr-extract: true

catalog:
  "@effect/language-service": ^0.84.2
  "@types/node": ^24
  bun: ^1.3.11
  effect: 4.0.0-beta.43
  effect-solutions: ^0.5.2
  typescript: ^5.9.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
